create extension if not exists pgcrypto;

create table if not exists public.game_config (
  id uuid primary key default gen_random_uuid(),
  key text not null,
  value jsonb not null default '{}'::jsonb,
  version text not null,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (key, version)
);

create table if not exists public.game_questions (
  id text not null,
  round text not null check (round in ('instinct', 'crisis', 'decisions')),
  question text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  metadata jsonb not null default '{}'::jsonb,
  version text not null,
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (id, version)
);

create table if not exists public.game_sessions (
  id uuid primary key,
  nickname text,
  started_at timestamptz not null,
  completed_at timestamptz,
  duration_ms integer check (duration_ms between 0 and 7200000),
  game_version text not null,
  question_version text not null,
  created_at timestamptz not null default now(),
  check (nickname is null or char_length(nickname) <= 24)
);

create table if not exists public.game_results (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null unique references public.game_sessions(id) on delete cascade,
  archetype text not null check (archetype in ('builder', 'problemSolver', 'explorer', 'designer', 'guardian', 'analyst')),
  builder_score smallint not null check (builder_score between 0 and 100),
  problem_solver_score smallint not null check (problem_solver_score between 0 and 100),
  explorer_score smallint not null check (explorer_score between 0 and 100),
  designer_score smallint not null check (designer_score between 0 and 100),
  guardian_score smallint not null check (guardian_score between 0 and 100),
  analyst_score smallint not null check (analyst_score between 0 and 100),
  total_score integer not null check (total_score between 0 and 600),
  game_version text not null,
  question_version text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.game_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.game_sessions(id) on delete cascade,
  event_type text not null,
  round smallint check (round between 1 and 4),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists game_sessions_started_at_idx on public.game_sessions (started_at desc);
create index if not exists game_results_created_at_idx on public.game_results (created_at desc);
create index if not exists game_results_archetype_idx on public.game_results (archetype);
create index if not exists game_events_session_idx on public.game_events (session_id, created_at);

alter table public.game_config enable row level security;
alter table public.game_questions enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_results enable row level security;
alter table public.game_events enable row level security;

revoke all on public.game_config, public.game_questions, public.game_sessions, public.game_results, public.game_events from anon, authenticated;
grant select on public.game_config, public.game_questions to anon, authenticated;

drop policy if exists "public reads active game config" on public.game_config;
create policy "public reads active game config"
  on public.game_config for select to anon, authenticated
  using (active = true);

drop policy if exists "public reads active game questions" on public.game_questions;
create policy "public reads active game questions"
  on public.game_questions for select to anon, authenticated
  using (active = true);

create or replace function public.start_booth_session(
  p_session_id uuid,
  p_nickname text,
  p_started_at timestamptz,
  p_game_version text,
  p_question_version text
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_session_id is null
    or p_started_at is null
    or char_length(coalesce(p_game_version, '')) not between 1 and 40
    or char_length(coalesce(p_question_version, '')) not between 1 and 40
    or char_length(coalesce(p_nickname, '')) > 24 then
    raise exception 'invalid booth session';
  end if;

  insert into public.game_sessions (id, nickname, started_at, game_version, question_version)
  values (p_session_id, nullif(trim(p_nickname), ''), p_started_at, p_game_version, p_question_version)
  on conflict (id) do nothing;
end;
$$;

create or replace function public.record_booth_checkpoint(
  p_session_id uuid,
  p_event_type text,
  p_round integer,
  p_metadata jsonb default '{}'::jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_session_id is null
    or p_round not between 1 and 4
    or char_length(coalesce(p_event_type, '')) not between 1 and 48
    or jsonb_typeof(coalesce(p_metadata, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid checkpoint';
  end if;

  insert into public.game_events (session_id, event_type, round, metadata)
  select p_session_id, p_event_type, p_round, coalesce(p_metadata, '{}'::jsonb)
  where exists (select 1 from public.game_sessions where id = p_session_id);
end;
$$;

create or replace function public.complete_booth_session(
  p_session_id uuid,
  p_nickname text,
  p_completed_at timestamptz,
  p_duration_ms integer,
  p_game_version text,
  p_question_version text,
  p_archetype text,
  p_builder_score integer,
  p_problem_solver_score integer,
  p_explorer_score integer,
  p_designer_score integer,
  p_guardian_score integer,
  p_analyst_score integer,
  p_total_score integer,
  p_events jsonb default '[]'::jsonb
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_session_id is null
    or p_completed_at is null
    or p_duration_ms not between 0 and 7200000
    or p_archetype not in ('builder', 'problemSolver', 'explorer', 'designer', 'guardian', 'analyst')
    or p_builder_score not between 0 and 100
    or p_problem_solver_score not between 0 and 100
    or p_explorer_score not between 0 and 100
    or p_designer_score not between 0 and 100
    or p_guardian_score not between 0 and 100
    or p_analyst_score not between 0 and 100
    or p_total_score not between 0 and 600
    or char_length(coalesce(p_nickname, '')) > 24
    or jsonb_typeof(coalesce(p_events, '[]'::jsonb)) <> 'array'
    or jsonb_array_length(coalesce(p_events, '[]'::jsonb)) > 50 then
    raise exception 'invalid completed session';
  end if;

  update public.game_sessions
  set nickname = nullif(trim(p_nickname), ''),
      completed_at = p_completed_at,
      duration_ms = p_duration_ms
  where id = p_session_id and completed_at is null;

  with inserted_result as (
    insert into public.game_results (
      session_id, archetype, builder_score, problem_solver_score, explorer_score,
      designer_score, guardian_score, analyst_score, total_score, game_version, question_version
    ) values (
      p_session_id, p_archetype, p_builder_score, p_problem_solver_score, p_explorer_score,
      p_designer_score, p_guardian_score, p_analyst_score, p_total_score, p_game_version, p_question_version
    )
    on conflict (session_id) do nothing
    returning id
  )
  insert into public.game_events (session_id, event_type, round, metadata)
  select
    p_session_id,
    left(coalesce(event->>'eventType', 'event'), 48),
    case when (event->>'round') ~ '^[1-4]$' then (event->>'round')::smallint else null end,
    case when jsonb_typeof(event->'metadata') = 'object' then event->'metadata' else '{}'::jsonb end
  from inserted_result, jsonb_array_elements(coalesce(p_events, '[]'::jsonb)) as event;
end;
$$;

create or replace function public.get_booth_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with today_sessions as (
    select * from public.game_sessions where started_at >= date_trunc('day', now())
  ),
  today_results as (
    select r.* from public.game_results r
    join today_sessions s on s.id = r.session_id
  ),
  archetypes as (
    select coalesce(jsonb_object_agg(archetype, amount), '{}'::jsonb) value
    from (select archetype, count(*) amount from today_results group by archetype) grouped
  )
  select jsonb_build_object(
    'started', (select count(*) from today_sessions),
    'completed', (select count(*) from today_sessions where completed_at is not null),
    'completion_rate', case when (select count(*) from today_sessions) = 0 then 0 else round(100.0 * (select count(*) from today_sessions where completed_at is not null) / (select count(*) from today_sessions)) end,
    'average_duration_ms', coalesce((select round(avg(duration_ms)) from today_sessions where completed_at is not null), 0),
    'archetypes', (select value from archetypes)
  );
$$;

revoke all on function public.start_booth_session(uuid, text, timestamptz, text, text) from public;
revoke all on function public.record_booth_checkpoint(uuid, text, integer, jsonb) from public;
revoke all on function public.complete_booth_session(uuid, text, timestamptz, integer, text, text, text, integer, integer, integer, integer, integer, integer, integer, jsonb) from public;
revoke all on function public.get_booth_stats() from public;

grant execute on function public.start_booth_session(uuid, text, timestamptz, text, text) to anon, authenticated;
grant execute on function public.record_booth_checkpoint(uuid, text, integer, jsonb) to anon, authenticated;
grant execute on function public.complete_booth_session(uuid, text, timestamptz, integer, text, text, text, integer, integer, integer, integer, integer, integer, integer, jsonb) to anon, authenticated;
grant execute on function public.get_booth_stats() to anon, authenticated;
